import 'package:flutter/material.dart';

class LegalNoticePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Legal Notice'),
        backgroundColor: const Color(0xFF6A1B9A),
      ),
      body: const SingleChildScrollView(
        padding: EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Legal Notice',
              style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 16),
            Text(
              'The ilili application is edited by the individual company Lahoucine LAPUNAIRE, registered with the RCS of Saint Denis under the number 951388073, whose head office is located at 9 Rue Charles Fourier, 91011 Évry-Courcouronnes.',
            ),
            Text(
              'Telephone number: 0652432127',
            ),
            Text(
              'E-mail address: lahoucinel.freelance@gmail.com',
            ),
            SizedBox(height: 16),
            Text(
              'The Publishing Director is: Lahoucine LAPUNAIRE',
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 16),
            Text(
              'Mobile applications are hosted on the App Store (Apple) and Google Play (Android). Both platforms offer a variety of features for app developers, including:',
            ),
            Text(
              'Application storage and distribution',
            ),
            Text(
              'Managing downloads and updates',
            ),
            Text(
              'Collect feedback and ratings',
            ),
            Text(
              'Revenue tracking',
            ),
            SizedBox(height: 16),
            Text(
              'App developers can submit their apps to the App Store and Google Play via a review process. Once the app is approved, it is available for download by users.',
            ),
            Text(
              'The App Store and Google Play charge developers a commission on revenues generated by their apps. The commission is 30% for paid apps and 15% for free apps.',
            ),
            SizedBox(height: 16),
            Text(
              'App Store:',
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
            Text(
              'Address: 1 Infinite Loop, Cupertino, CA 95014, United States',
            ),
            Text(
              'Phone number: 1-408-996-1010',
            ),
            SizedBox(height: 16),
            Text(
              'Google Play:',
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
            Text(
              'Address: 1600 Amphitheatre Parkway, Mountain View, CA 94043, United States',
            ),
            Text(
              'Phone number: 1-650-253-0000',
            ),
          ],
        ),
      ),
    );
  }
}

void main() {
  runApp(MaterialApp(
    home: LegalNoticePage(),
  ));
}
